# sweep id: 88y5jpl5
program: alpha_opt/experiments/botorch_optimize.py
method: grid
metric:
    name: loss
    goal: minimize
command:
  - ${env}
  - python
  - ${program}
  - alpha_opt/configs/garabedian_linear_pressure.yaml
parameters:
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]